version: '3.4'

services:
  crimeservice:
    image: ${DOCKER_REGISTRY-}crimeservice
    build:
      context: .
      dockerfile: CrimeService/Dockerfile

  policeservice.api:
    image: ${DOCKER_REGISTRY-}policeserviceapi
    build:
      context: .
      dockerfile: PoliceService.API/Dockerfile

  sql_database:
    image: "mcr.microsoft.com/mssql/server:2017-latest"

  mongo_database:
    image: mongo

volumes:
  sql_volume:
  mongo_volume:
